### ISSUE TITLE
Problem when Vessel has Launch Stability Enhancer

### ISSUE THREAD

**Issue by gomker** [PapaJoesSoup/VesselMover#4]
Using the Spawn Vessel function and the craft has the TT18-Launch Stability enhancer  attached will cause the vessel to spawn attached to the ground.

Issue is not that bad as you can just click "Move Vessel" and the clamps disengage however, if the vessel is a boat over water , the boat may spawn on the ocean floor which can  make some odd effects if you are far from shore

**Comment by DoctorDavinci** [comment]
The Vessel Mover 'spawn vessel' function is only designed to spawn a saved vessel.

It is out of the scope of this mod to actually scan your vessel for launch stability enhancers and then remove them from your saved vessel before spawning it

**Comment by gomker** [comment]
I am not sure I understand what you mean by "spawn a saved vessel" What other vessel could you spawn other than a "saved" one?

The mod must be doing something that triggers launch clamps as I described "move vessel" disengages them automatically, but does not increment the launch stage. 

See the code [here ](https://github.com/BahamutoD/VesselMover/blob/7656ec2a319336c21e18234af957f9d2fb5e6fe7/VesselMove.cs#L380)

**Comment by PapaJoesSoup** [comment]
I'm looking at this issue now

**Comment by PapaJoesSoup** [comment]
Ok, I've done some testing.  What I see is this:

When spawned on the ocean floor, if you click move, it instantly goes to the surface and sits 35 meters above the surface... so that is good.  If you release the clamps on the ocean floor, the vessel begins to rise to the surface... as expected.

The question is, what behavior would we like to have.  I suggest we keep the original behavior as an option, as there are advantages to being able to spawn underwater.

I also suggest by setting a switch, we allow the vessel to spawn above the surface of the water... IF i can get the clamps to anchor to the water's surface... I would think I could, as it should have a collider

Thoughts?

**Comment by gomker** [comment]
I did not consider spawning on the ocean floor as described, I was testing boats at the time. I do see the benefit in this for submarine testing which I am doing now for Large Boat Packs.

A "spawn on water" option would be the best compromise , this could be quite useful for spawning large boats and counteract similar issues you were working on with VesselMover.

**Comment by gomker** [comment]
1.2 Introduced some issues with spawning from protovessel that changed this behavior. Newest updates solve this
