### ISSUE TITLE
krakensbane

### ISSUE THREAD

**Issue by Nerfclasher** [PapaJoesSoup/VesselMover#9]
https://www.dropbox.com/s/n0k7rhsql28ijdi/KSP%20%282%29.log?dl=0

**Comment by PapaJoesSoup** [comment]
??

**Comment by DoctorDavinci** [comment]
Ok, so this tells me nothing other than that you are testing with mods that we do not support and that you are unable to string together even a coherent sentence that explains what you are referring to other than the title of your issue which is Krakensbane ... Do you mean that your log file is the bane of the Kraken or ..... Hell, I'm done ..... If you are unable to give us the information we require to duplicate the issue or even at the very least what the issue is then please don't bother bringing it to our attention as it creates more frustration than actual progress

I'm saying this from me and not the BDAc team so do not hold them accountable for my words ... @Nerfclasher - Step up

Please give us more information than a link to a log file

**Comment by PapaJoesSoup** [comment]
Closed.  Lack of information.

**Comment by Nerfclasher** [comment]
@PapaJoesSoup It is where vessel mover bugs up with is randomly accelerating the craft we I have clearly did not put it down and the logs are evidence

**Comment by Nerfclasher** [comment]
related to maybe #8
